# Generated by Django 3.0.7 on 2020-07-02 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Dia y Hora')),
                ('comment', models.TextField()),
                ('pediatrician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoinments', to='accounts.Pediatrician')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appoinments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'unique_together': {('user', 'pediatrician', 'date')},
            },
        ),
    ]
